// Auto-generated by Payload. Do not edit manually.
// This file will be regenerated on every startup.
// Create a stub for TypeScript until the real import map is generated.
const importMap: Record<string, unknown> = {};

export default importMap;
export { importMap };
